### ISSUE TITLE
Support statement-like preprocessor directives inside functions.

### ISSUE THREAD

**Issue by DiThi** [lammas/glsl-man#11]
It seems it supports top level directives. And while directive inside statements/expressions may be too much to ask, directives between statements should be relatively easy to support.

**Comment by lammas** [comment]
If I understand the problem correctly it seems the parser doesn't handle preprocessor statements that have leading whitespace. This I can probably fix.

Supporting directives inside or on the same line with regular statements seems tricky though. Due to the preprocessor syntax if there's no newline at the end of a preprocessor directive, finding the start of the next actual statement seems full of special cases and I don't think is worth the effort.

Correct me if I got something wrong.

**Comment by DiThi** [comment]
@lammas I'd like the string writer to spit out the preprocessor directives as-is. In the code I think it's trying to parse the ifdefs and elses as havings its own body, but I'd prefer if they're treated as bare statements. In any case I'm not getting any directive back and stuff fails because it has no `#extension`s. But only for some large shaders, for short examples I do get directives. I'm confused.

All directives are in its own line without leading whitespace.

**Comment by DiThi** [comment]
I'm sorry! I left some code that replaces directives by comments.

**Comment by DiThi** [comment]
@lammas It works now for my purposes, by finding the relevant nodes inside ifdef "bodies". I think we should have a separate parser/writer for the preprocessor.

**Comment by DiThi** [comment]
I think I can close this one, I'm only removing the directive in the middle of an expression and the rest seem to work now.
